#!/usr/bin/env ruby

$LOAD_PATH << "lib"

require 'print_month.rb'

m = ARGV[0]
y = ARGV[1]


if y != nil
  puts_month_days(m, y)
else
  i = 1
  y = m
  12.times do
    puts_month_days(i, y)
    i += 1
  end
end
