#!/usr/bin/env ruby

$LOAD_PATH << "lib"

require 'print_month.rb'
require 'print_months.rb'
require 'print_3_rows.rb'
require 'print_4_rows.rb'
require 'print_2_rows.rb'

m = ARGV[0]
y = ARGV[1]

if m == "r3"
  print_3_rows(y)
elsif m == "r2"
  print_2_rows(y)
else
if y != nil
  if m == "r4"
    y = m
    print_4_rows(y)
  else
    puts_month_days(m, y)
  end
else
  y = m
  print_4_rows(y)
end
end
